
server:
  port: 8080
spring:
  application:
    name: shard-jdbc-starter

mybatis:
  mapper-locations: classpath:mapper/base/*.xml
  type-aliases-package: com.linktree.sikehome.entity

sharding:
  jdbc:
    datasource:
      names: itsource
      itsource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://120.78.0.90:3306/itsource?useUnicode=true&characterEncoding=utf-8
        username: root
        password: guolei1234

    config:
      sharding:
        props:
          sql.show: true
        tables:
          address:
            key-generator-column-name: id
            actual-data-nodes: itsource.address
            database-strategy:
              inline:
                sharding-column: lit
                algorithm-expression: ds${lit % 2}