
server:
  port: 8080
spring:
  application:
    name: shard-jdbc-starter
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.linktree.sikehome.entity

sharding:
  jdbc:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://120.78.0.90:3306/itsource?useUnicode=true&characterEncoding=utf-8
        username: root
        password: guolei1234
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://120.78.0.90:3306/itsource0?useUnicode=true&characterEncoding=utf-8
        username: root
        password: guolei1234
    config:
      sharding:
        props:
          sql.show: false
        tables:
          t_user:
            key-generator-column-name: id
            actual-data-nodes: ds${0..1}.t_user${0..1}
            database-strategy:
              inline:
                sharding-column: city_id
                algorithm-expression: ds${city_id % 2}
            table-strategy:
              inline:
                sharding-column: sex
                algorithm-expression: t_user${sex % 2}
          address:
            key-generator-column-name: id
            actual-data-nodes: ds${0..1}.address
            database-strategy:
              inline:
                sharding-column: lit
                algorithm-expression: ds${lit % 2}