
server:
  port: 8080
spring:
  application:
    name: shard-jdbc-starter

# mybatis xml配置路径 这里使用自动生成
mybatis:
  mapper-locations: classpath:mapper/base/*.xml
  type-aliases-package: com.linktree.sikehome.entity

###数据源名称，多数据源以逗号分隔，目前只创建了itsource一个。。。。后续扩充
sharding:
  jdbc:
    datasource:
      names: itsource
      # 数据源ds0
      itsource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://120.78.0.90:3306/itsource #郭老师得数据库
        username: root
        password: guolei1234

    config:
      sharding:
        props:
          sql.show: true
        tables:
#          t_user:  #t_user表
#            key-generator-column-name: id  #主键
#            actual-data-nodes: ds${0..1}.t_user${0..1}    #数据节点,均匀分布
#            database-strategy:   #分库策略
#              inline: #行表达式
#                sharding-column: city_id        #列名称，多个列以逗号分隔
#                algorithm-expression: ds${city_id % 2}    #按模运算分配
#            table-strategy:  #分表策略
#              inline: #行表达式
#                sharding-column: sex
#                algorithm-expression: t_user${sex % 2}
          address:
            key-generator-column-name: id
            actual-data-nodes: itsource.address
            database-strategy:
              inline:
                sharding-column: lit
                algorithm-expression: ds${lit % 2}